import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import '@mantine/core/styles.css'
import {
  createTheme,
  MantineProvider,
  ColorSchemeScript,
  mantineHtmlProps,
  Container, SimpleGrid, Image, Title, Text, Button,
} from '@mantine/core'
import {GeneralHeader} from "@/app/components/header/general-header";
import {GeneralFooter} from "@/app/components/footer/general-footer";
import classes from "@/app/(root)/NotFoundImage.module.css";
import image from "@/app/(root)/error.svg";


const theme = createTheme({
  /** Put your mantine theme override here */
})

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    default: 'default Made by Minipingu',
    template: '%s | (template) Made by Minipingu',
  },
  description: 'Generated by create next app',
}

type params = {
  children: React.ReactNode
}

export default function RootLayout({ children }: params) {
  return (
    <html lang='en' {...mantineHtmlProps}>
    <head>
      <ColorSchemeScript />
      <link rel='shortcut icon' href='/favicon.svg' />
      <meta
        name='viewport'
        content='minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no'
      />
    </head>
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <MantineProvider defaultColorScheme='dark' theme={theme}>
      <GeneralHeader />
      <Container className={classes.root}>
        <SimpleGrid spacing={{ base: 40, sm: 80 }} cols={{ base: 1, sm: 2 }}>
          <Image src={image.src} className={classes.mobileImage} />
          <div>
            <Title className={classes.title}>
              Something is not right...
            </Title>
            <Text c='dimmed' size='lg'>
              Page you are trying to open does not exist. You may have
              mistyped the address, or the page has been moved to another
              URL. If you think this is an error contact support.
            </Text>
            <Button
              variant='outline'
              size='md'
              mt='xl'
              className={classes.control}>
              Get back to home page
            </Button>
          </div>
          <Image src={image.src} className={classes.desktopImage} />
        </SimpleGrid>
      </Container>
      <GeneralFooter />
    </MantineProvider>
    </body>
    </html>
  )
}
