import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
	title: 'Blog',
	description: 'Generated by create next app',
}

const Blog = () => {
	return <div>Blog</div>
}

export default Blog
